### ISSUE TITLE
Sofistik Project Component "Stream dat" doubt

### ISSUE THREAD

**Issue by GonzaloNavarroMunoz** [SOFiSTiK/gh_sofistik#13]
Hi! 

First of all, congrats on the recently published components for GH, they are pretty good. 

I have one question regarding the "Sofistik Project" component that I haven't been able to find in the command reference page (https://www.sofistik.de/documentation/2020/en/rhino_interface/grasshopper/components/SOFiSTiKProject.html): what is the purpose of the option "Stream dat"? I understand that it should be something easy to know but I haven't been able to figure it out (in contrast with the option "Silent calculation" which is self-explanatory for me).

Thanks very much

Regards

**Comment by emanuelknapp** [comment]
Hi,

Thank you very much for your feedback. I am very happy that you like recent developments.
The option "Stream dat" determines if the generated teddy output is streamed into the .dat file on every change or not.
So, if you use a SSD workflow, you might have included the .dat file in your SSD project and when a change inside gh occures you want to turn "Stream dat" on, so that this change is directly streamed to the .dat file.
If you just use the calculation functionality of the "Project" component inside grasshopper, you dont need the streaming, because on pressing calculate, the information will be streamed to the .dat file at this moment.
I hope this clarifies the functionality.
Thanks again for your feedback.

With kind regards

Emanuel Knapp
